version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 4443:443
    volumes:
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/sites-available/default:/etc/nginx/conf.d/default.conf
      - ./nginx/private:/etc/ssl/private
      - ./nginx/src:/var/www/html
    networks:
      challenge3:
        ipv4_address: 172.30.0.5
    depends_on:
     - webapp
  webapp:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    expose:
      - "8080"
    volumes:
      - ./apache/src:/var/www/html
    networks:
      challenge3:
        ipv4_address: 172.30.0.6
    depends_on:
      - es01
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es01
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      challenge3:
        ipv4_address: 172.30.0.7
    expose:
      - "9200"
volumes:
  data01:
    driver: local
networks:
  challenge3:
    ipam:
      config:
        - subnet: 172.30.0.0/24